[package]
name = "zk_dtp"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
risc0-zkvm = { version = "1.2.2", default-features = false, features = ['std'] }
